name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up cache for Chromium and dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache
          /usr/local/bin/chromium
        key: ${{ runner.os }}-chromium-${{ hashFiles('package-lock.json', 'run_tests.sh') }}
        restore-keys: |
          ${{ runner.os }}-chromium-

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser x11-apps

    - name: Run Tests
      run: |
        sudo Xvfb :99 -ac &
        export DISPLAY=:99
        bash run_tests.sh

    - name: Check Exit Code
      if: failure()
      run: echo "Tests failed with exit code $?"

